### ISSUE TITLE
Suggestion. Add support for webp

### ISSUE THREAD

**Issue by ristaloff** [roberttidey/userland#6]
Would it be possible to output .webp files instead of .jpeg from raspimjpeg?
The only reason is to save bandwidth when serving the images through a web server.
I guess you could let raspimjpeg output .jpeg then convert that to .webp. But I think it would be much better perfrmance-wise to save it as .webp directly.

The reason I want this is to get the network traffic down when using the RPI-cam-web-interface.

This is just an idea, I do not have a good knowledge of the .webp format. 

https://developers.google.com/speed/webp/
https://developers.google.com/speed/webp/docs/api

**Comment by roberttidey** [comment]
I think this would need post conversion. We get jpg data direct from the GPU encoder so that is not consuming any CPU time. Adding on a post-conversion would have to be done in the CPU and might consume a fair bit of processing. The other concern would be that not all browsers support this natively.

One can optimise the bandwidth in the current system by adjusting width, quality, and divider ratio. I know that's not the same as a more efficient format but it does allow connections over smaller bandwidth channels.

**Comment by ristaloff** [comment]
Ok, thanks for your reply.
